kind: pipeline
type: docker
name: default

steps:
- name: build
  image: alpine/helm:2.15.1
  commands:
  - ls
  - helm init --client-only
  - mkdir -p ~/.helm/repository
  - helm package gitea
  - helm repo index . --url https://yaamai.github.io/charts
  - ls
  - git checkout -b gh-pages
