kind: pipeline
type: docker
name: default

steps:
- name: build
  image: alpine/helm:2.15.1
  commands:
  - helm init --client-only
  - helm package gitea
  - helm repo index . --url https://yaamai.github.io/charts
- name: publish
  image: alpine/git
  commands:
  - git checkout -b gh-pages
  - git add -A .
  - git commit -m "Update"
