apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traefik.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "traefik.name" . }}
    helm.sh/chart: {{ include "traefik.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "traefik.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "traefik.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --configFile=/etc/traefik/traefik.toml
        ports:
          - name: http
            containerPort: 8000
            protocol: TCP
          - name: traefik
            containerPort: 9000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /ping
            port: traefik
        readinessProbe:
          httpGet:
            path: /ping
            port: traefik
        volumeMounts:
        - mountPath: /etc/traefik
          name: static-config
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: static-config
        configMap:
          name: {{ default (include "traefik.fullname" .) }}-static
