# to edit yaml via kubectl prettily, plz avoid trailing space (#36222)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "traefik.fullname" . }}-dynamic
  labels:
    app: "{{ template "traefik.fullname" . }}"
    chart: "{{ template "traefik.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  tls.toml: |
    [tls]
      [[tsl.options]
        [tls.options.default]
          minVersion = "VersionTLS12"
          [tls.options.default.clientAuth]
            caFiles = ["ca.crt"]
            clientAuthType = "RequireAndVerifyClientCert"
  ca.crt: ""
