apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "traefik.name" . }}
    helm.sh/chart: {{ include "traefik.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: web
      protocol: TCP
      name: web
    - port: {{ .Values.service.websecure.port }}
      targetPort: websecure
      protocol: TCP
      name: websecure
    - port: {{ .Values.service.traefik.port }}
      targetPort: traefik
      protocol: TCP
      name: traefik
  selector:
    app.kubernetes.io/name: {{ include "traefik.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
