# to edit yaml via kubectl prettily, plz avoid trailing space (#36222)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "traefik.fullname" . }}-static
  labels:
    app: "{{ template "traefik.fullname" . }}"
    chart: "{{ template "traefik.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  traefik.toml: |
    logLevel = "DEBUG"
    debug = true
    defaultEntryPoints = ["https"]
    insecureSkipVerify = true
    
    [entryPoints]
      [entryPoints.api]
        address = ":{{ .Values.ports.traefik.port }}"
    
      [entryPoints.http]
        address = ":{{ .Values.ports.web.port }}"
        compress = true
    
        [entryPoints.http.redirect]
          entryPoint = "https"
    
      [entryPoints.https]
        address = ":{{ .Values.ports.websecure.port }}"
        compress = true
    
        [entryPoints.https.tls]
          minVersion = "VersionTLS11"
          cipherSuites = [
            "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
            "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA"
          ]
    
          {{- if .Values.ssl.defaultCertSecretName }}
          [[entryPoints.https.tls.certificates]]
            CertFile = "/ssl/default/tls.crt"
            KeyFile = "/ssl/default/tls.key"
          {{- end }}

          {{- if .Values.ssl.mtls.clientCaSecretName }}
          [entryPoints.https.tls.ClientCA]
            files = ["/ssl/client-ca/ca.crt"]
            optional = {{ .Values.ssl.mtls.optional }}
          {{- end }}
    [kubernetes]
    [api]
      entryPoint = "api"
      dashboard = true
      debug = true
