# to edit yaml via kubectl prettily, plz avoid trailing space (#36222)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gitea.fullname" . }}
  labels:
    app: "{{ template "gitea.fullname" . }}"
    chart: "{{ template "gitea.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  app.ini: {{ .Values.config.app | quote }}
