# to edit yaml via kubectl prettily, plz avoid trailing space (#36222)
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "gitea.fullname" . }}
  labels:
    app: "{{ template "gitea.fullname" . }}"
    chart: "{{ template "gitea.chart" . }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
  app.ini: |
    APP_NAME = Gitea: Git with a cup of tea
    RUN_MODE = prod
    RUN_USER = git
    
    [repository]
    ROOT = /data/git/repositories
    
    [repository.local]
    LOCAL_COPY_PATH = /data/gitea/tmp/local-repo
    
    [repository.upload]
    TEMP_PATH = /data/gitea/uploads
    
    [server]
    APP_DATA_PATH    = /data/gitea
    SSH_DOMAIN       = localhost
    HTTP_PORT        = 3000
    ROOT_URL         = http://localhost:3000/
    DISABLE_SSH      = false
    SSH_PORT         = 22
    LFS_START_SERVER = true
    LFS_CONTENT_PATH = /data/git/lfs
    DOMAIN           = localhost
    LFS_JWT_SECRET   = %LFS_JWT_SECRET%
    OFFLINE_MODE     = true
    
    [database]
    PATH     = /data/gitea/gitea.db
    DB_TYPE  = sqlite3
    HOST     = localhost:3306
    NAME     = gitea
    USER     = root
    ; PASSWD   =
    SSL_MODE = disable
    CHARSET  = utf8
    
    [indexer]
    ISSUE_INDEXER_PATH = /data/gitea/indexers/issues.bleve
    
    [session]
    PROVIDER_CONFIG = /data/gitea/sessions
    PROVIDER        = file
    
    [picture]
    AVATAR_UPLOAD_PATH            = /data/gitea/avatars
    REPOSITORY_AVATAR_UPLOAD_PATH = /data/gitea/repo-avatars
    DISABLE_GRAVATAR              = true
    ENABLE_FEDERATED_AVATAR       = false
    
    [attachment]
    PATH = /data/gitea/attachments
    
    [log]
    ROOT_PATH = /data/gitea/log
    MODE      = console
    LEVEL     = trace
    STACKTRACE_LEVEL = trace
    
    [security]
    INSTALL_LOCK   = true
    INTERNAL_TOKEN = %INTERNAL_TOKEN%
    SECRET_KEY     = %SECRET_KEY%
    
    [service]
    DISABLE_REGISTRATION              = false
    REQUIRE_SIGNIN_VIEW               = false
    REGISTER_EMAIL_CONFIRM            = false
    ENABLE_NOTIFY_MAIL                = false
    ALLOW_ONLY_EXTERNAL_REGISTRATION  = false
    ENABLE_CAPTCHA                    = false
    DEFAULT_KEEP_EMAIL_PRIVATE        = false
    DEFAULT_ALLOW_CREATE_ORGANIZATION = true
    DEFAULT_ENABLE_TIMETRACKING       = true
    NO_REPLY_ADDRESS                  = noreply.example.org
    
    [oauth2]
    JWT_SECRET = %JWT_SECRET%
    
    [mailer]
    ENABLED = false
    
    [openid]
    ENABLE_OPENID_SIGNIN = true
    ENABLE_OPENID_SIGNUP = true
